/* gci.h generated by valac 0.48.0, the Vala compiler, do not modify */

#ifndef __GCI_GCI_H__
#define __GCI_GCI_H__

#include <glib-object.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS

#define GCI_TYPE_ENTRY_CONTROLLER (gci_entry_controller_get_type ())
#define GCI_ENTRY_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GCI_TYPE_ENTRY_CONTROLLER, GCiEntryController))
#define GCI_ENTRY_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GCI_TYPE_ENTRY_CONTROLLER, GCiEntryControllerClass))
#define GCI_IS_ENTRY_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GCI_TYPE_ENTRY_CONTROLLER))
#define GCI_IS_ENTRY_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GCI_TYPE_ENTRY_CONTROLLER))
#define GCI_ENTRY_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GCI_TYPE_ENTRY_CONTROLLER, GCiEntryControllerClass))

typedef struct _GCiEntryController GCiEntryController;
typedef struct _GCiEntryControllerClass GCiEntryControllerClass;
typedef struct _GCiEntryControllerPrivate GCiEntryControllerPrivate;

struct _GCiEntryController {
	GObject parent_instance;
	GCiEntryControllerPrivate * priv;
};

struct _GCiEntryControllerClass {
	GObjectClass parent_class;
};

GType gci_entry_controller_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GCiEntryController, g_object_unref)
GCiEntryController* gci_entry_controller_new_for_entry (GtkEntry* entry);
GCiEntryController* gci_entry_controller_construct_for_entry (GType object_type,
                                                              GtkEntry* entry);
GCiEntryController* gci_entry_controller_new (void);
GCiEntryController* gci_entry_controller_construct (GType object_type);
GtkEntry* gci_entry_controller_get_entry (GCiEntryController* self);
void gci_entry_controller_set_entry (GCiEntryController* self,
                                     GtkEntry* value);

G_END_DECLS

#endif
